### PR TITLE
Fix: allow OAuth callback to work on remote servers (fixes #186)

### LINKED ISSUE #186: Auth is impossible on a remote server
I'm trying out ironclaw on a VPS, but can't authenticate with either google or github because it uses 127.0.0.1 for callbacks, which I can't access from browser on my local machine. It's probably possible to set up reverse proxy / configure firewall + edit url manually to fix the redirect, but I feel like the onboarding script should take care of all that. Am I supposed to only ever run it on a local machine, with VPS not officially supported?

Image

### PR DESCRIPTION
**Pull request by nlok5923**
## Problem

When running ironclaw on a remote server, the OAuth callback URL is hardcoded to `http://127.0.0.1:9876` in two places — NEAR AI login (`session.rs`) and MCP server auth (`mcp/auth.rs`). The OAuth provider redirects the user's browser to this URL, which only works locally.
On a VPS, the browser gets a connection refused.

  ## Fix

  - Added `callback_host()` to `oauth_defaults` — reads `OAUTH_CALLBACK_HOST` env var, defaults to `127.0.0.1` (no behaviour change for local users)
  - When a non-loopback host is configured, `bind_callback_listener()` binds to `0.0.0.0` so the port is reachable from outside the machine
  - `session.rs` and `mcp/auth.rs` now use `callback_host()` instead of hardcoded addresses

  ## Usage on a remote server

  ```bash
  export OAUTH_CALLBACK_HOST=<your-server-ip>
  ironclaw login
  # Browser opens: http://<your-server-ip>:9876/auth/callback

  No change needed for local users — default behaviour is preserved.
  ```

### CODE REVIEW

File: src/llm/session.rs [hunk 1]
```diff
@@ -233,7 +233,11 @@ impl SessionManager {
                 reason: e.to_string(),
             })?;
 
-        let callback_url = format!("http://127.0.0.1:{}", OAUTH_CALLBACK_PORT);
+        let callback_url = format!(
+            "http://{}:{}",
+            oauth_defaults::callback_host(),
+            OAUTH_CALLBACK_PORT
+        );
```
[the remark this answers is not in the document]
Comment (nlok5923) [reply src/llm/session.rs]: Added a prominent warning when a non-loopback host is configured, explaining the risk and recommending SSH port forwarding as the safer alternative (ssh -L 9876:127.0.0.1:9876 user@host). Full TLS would require certificate management which is out of scope for this fix.

File: src/tools/mcp/auth.rs [hunk 2]
```diff
@@ -380,7 +380,11 @@ pub async fn authorize_mcp_server(
 ) -> Result<AccessToken, AuthError> {
     // Find an available port for the callback first (needed for DCR)
     let (listener, port) = find_available_port().await?;
-    let redirect_uri = format!("http://localhost:{}/callback", port);
+    let redirect_uri = format!(
+        "http://{}:{}/callback",
+        oauth_defaults::callback_host(),
+        port
+    );
```
[the remark this answers is not in the document]
Comment (nlok5923) [reply src/tools/mcp/auth.rs]: Same fix applied here a warning is now printed when a remote host is detected, with the SSH tunnel suggestion. Users are no longer silently exposed to this risk.

File: src/cli/oauth_defaults.rs [hunk 3]
```diff
@@ -80,33 +105,50 @@ pub enum OAuthCallbackError {
...
+                if e.kind() == std::io::ErrorKind::AddrInUse {
+                    OAuthCallbackError::PortInUse(OAUTH_CALLBACK_PORT, e.to_string())
+                } else {
+                    OAuthCallbackError::Io(e.to_string())
+                }
+            })
+    } else {
+        // Remote mode: bind to all interfaces so the port is reachable from outside.
+        let addr = format!("0.0.0.0:{}", OAUTH_CALLBACK_PORT);
+        TcpListener::bind(&addr).await.map_err(|e| {
```
[the remark this answers is not in the document]
Comment (nlok5923) [reply src/cli/oauth_defaults.rs]: Fixed now binds to {host}:{PORT} instead of 0.0.0.0:{PORT} as suggested. Also extracted a bind_error() helper to remove the duplicated error mapping logic noted in the review.

File: src/cli/oauth_defaults.rs [hunk 4]
```diff
@@ -66,12 +66,37 @@ pub const OAUTH_CALLBACK_PORT: u16 = 9876;
...
+        .unwrap_or_else(|| format!("http://{}:{}", callback_host(), OAUTH_CALLBACK_PORT))
+}
+
+/// Returns the hostname used in OAuth callback URLs.
+///
+/// Reads `OAUTH_CALLBACK_HOST` from the environment (default: `127.0.0.1`).
+///
+/// **Remote server usage:** set `OAUTH_CALLBACK_HOST` to the server's public
+/// IP or hostname so the OAuth redirect reaches your local browser.  The
+/// callback listener will then bind to `0.0.0.0` instead of `127.0.0.1` to
```
Comment (serrrfirat) [inline src/cli/oauth_defaults.rs]: **Medium Severity** — Docstring says `0.0.0.0` but code binds to specific host

The docstring for `callback_host()` (line 83) states:

> The callback listener will then bind to `0.0.0.0` instead of `127.0.0.1` to accept connections from outside the machine.

However, the actual implementation in `bind_callback_listener()` (line 157-159) does the opposite — it binds to the **specific host address**, not `0.0.0.0`:

```rust
// Remote mode: bind to the specific configured host address only,
// not 0.0.0.0, to limit exposure to the intended interface.
let addr = format!("{}:{}", host, OAUTH_CALLBACK_PORT);
```

This discrepancy is misleading. A user behind NAT who sets `OAUTH_CALLBACK_HOST` to their public IP (e.g., `203.0.113.10`) expecting `0.0.0.0` behavior will get a bind failure if that IP isn't assigned to a local network interface. The code's behavior is actually *safer* than documented, but the docs should match reality.

**Suggested fix:** Change the docstring to:
> The callback listener will then bind to the configured host address instead of `127.0.0.1` to accept connections directed to that interface.

File: src/llm/session.rs [hunk 5]
```diff
@@ -239,6 +241,21 @@ impl SessionManager {
 
         let cb_url = oauth_defaults::callback_url();
 
+        let host = oauth_defaults::callback_host();
+
+        // Warn when the callback is served over plain HTTP to a remote host.
+        // Tokens travel unencrypted; SSH port forwarding is a safer alternative:
+        //   ssh -L 9876:127.0.0.1:9876 user@your-server
+        if !oauth_defaults::is_loopback_host(&host) {
```
Comment (serrrfirat) [inline src/llm/session.rs]: **Low Severity** — HTTP warning shown before auth method selection

The HTTP security warning is printed at line 249-256 *before* the user selects their auth method. If the user ends up choosing option 4 (NEAR AI Cloud API key), the OAuth callback is never used, making the HTTP/unencrypted-token warning irrelevant noise that may confuse the user.

**Suggested fix:** Move the warning to after the auth method selection, only showing it for OAuth-based options (1, 2, 3). Something like:

```rust
// After reading choice, before binding the listener:
if matches!(auth_method, 1 | 2 | 3) && !oauth_defaults::is_loopback_host(&host) {
    println!("Warning: OAuth callback is using plain HTTP...");
    // ...
}
```

File: src/cli/oauth_defaults.rs [hunk 6]
```diff
@@ -66,12 +66,37 @@ pub const OAUTH_CALLBACK_PORT: u16 = 9876;
...
+/// accept connections from outside the machine.
+///
+/// # Example
+///
+/// ```bash
+/// export OAUTH_CALLBACK_HOST=203.0.113.10
+/// ironclaw login
+/// # Opens: http://203.0.113.10:9876/auth/callback
+/// ```
```
Comment (serrrfirat) [inline src/cli/oauth_defaults.rs:94]: **Low Severity** — No test for `OAUTH_CALLBACK_HOST` env var

The existing tests cover `IRONCLAW_OAUTH_CALLBACK_URL` override (`test_callback_url_env_override`) and default behavior, but there are no tests for the new `OAUTH_CALLBACK_HOST` env var path. This is the primary new mechanism introduced by this PR.

**Suggested fix:** Add tests similar to the existing override tests:

```rust
#[test]
fn test_callback_host_default() {
    let _guard = ENV_MUTEX.lock().expect("env mutex poisoned");
    let original = std::env::var("OAUTH_CALLBACK_HOST").ok();
    unsafe { std::env::remove_var("OAUTH_CALLBACK_HOST"); }
    assert_eq!(callback_host(), "127.0.0.1");
    // restore...
}

#[test]
fn test_callback_host_env_override() {
    let _guard = ENV_MUTEX.lock().expect("env mutex poisoned");
    unsafe { std::env::set_var("OAUTH_CALLBACK_HOST", "203.0.113.10"); }
    assert_eq!(callback_host(), "203.0.113.10");
    // Also verify callback_url() incorporates the custom host:
    let url = callback_url();
    assert!(url.contains("203.0.113.10"));
    // restore...
}

#[test]
fn test_is_loopback_host() {
    assert!(is_loopback_host("127.0.0.1"));
    assert!(is_loopback_host("::1"));
    assert!(is_loopback_host("localhost"));
    assert!(is_loopback_host("LOCALHOST"));
    assert!(!is_loopback_host("203.0.113.10"));
    assert!(!is_loopback_host("example.com"));
}
```

File: src/cli/oauth_defaults.rs [hunk 7]
```diff
@@ -66,12 +66,37 @@ pub const OAUTH_CALLBACK_PORT: u16 = 9876;
...
+pub fn callback_host() -> String {
+    std::env::var("OAUTH_CALLBACK_HOST").unwrap_or_else(|_| "127.0.0.1".to_string())
+}
+
+/// Returns `true` if `host` is a loopback address that only accepts local connections.
```
Comment (serrrfirat) [inline src/cli/oauth_defaults.rs:99]: **Nit** — `is_loopback_host` doesn't cover the full loopback range

`is_loopback_host` checks `127.0.0.1`, `::1`, and `localhost` but doesn't cover the full `127.0.0.0/8` loopback range (e.g., `127.0.0.2`, `127.255.255.254`). While unlikely in practice, someone binding to another loopback address would unexpectedly get remote-mode behavior.

**Optional improvement:**

```rust
pub fn is_loopback_host(host: &str) -> bool {
    if host.eq_ignore_ascii_case("localhost") {
        return true;
    }
    host.parse::<std::net::IpAddr>()
        .map(|ip| ip.is_loopback())
        .unwrap_or(false)
}
```

This covers the full `127.0.0.0/8` range for IPv4 and `::1` for IPv6 in one shot.

File: src/cli/oauth_defaults.rs (hunk 4 above)
Comment (nlok5923) [reply src/cli/oauth_defaults.rs]: The docstring was left over from an earlier iteration where we bound to 0.0.0.0. Updated it to accurately describe the actual behavior binds to the specific configured address
 
 added a note about the plain-HTTP risk with a pointer to SSH port forwarding.

File: src/llm/session.rs (hunk 5 above)
Comment (nlok5923) [reply src/llm/session.rs]: Fixed. The warning is now shown only after the user selects an OAuth option (1 or 2), right before the listener
  binds. Users who pick option 4 (API key) will never see it.

File: src/cli/oauth_defaults.rs (hunk 6 above)
Comment (nlok5923) [reply src/cli/oauth_defaults.rs:94]: Added test_callback_host_default and test_callback_host_env_override. The override test also asserts that
`callback_url()` incorporates the custom host in its fallback path 

(i.e. when IRONCLAW_OAUTH_CALLBACK_URL is not set).

File: src/cli/oauth_defaults.rs (hunk 7 above)
Comment (nlok5923) [reply src/cli/oauth_defaults.rs:99]: Adopted your suggestion. Now uses `IpAddr::is_loopback()` which covers the full `127.0.0.0/8` range for
IPv4 and ::1 for IPv6 in one shot. Added assertions for `127.0.0.2` and `127.255.255.254` in the test.
