### PR TITLE
fix(security): harden approval thread safety (TOCTOU + error handling)

### LINKED ISSUE #1486: [CRITICAL] TOCTOU race condition in approval thread resolution
## [CRITICAL:95] Issue Found by Staging CI Review

**Severity:** CRITICAL
**Confidence:** 95/100
**PR comment:** https://github.com/nearai/ironclaw/pull/1483#issuecomment-4100594194

### Description
TOCTOU race condition in approval thread resolution

---
*Auto-created by staging-ci Claude Code review*

### LINKED ISSUE #1487: [HIGH] Incomplete fallback logic for non-existent approval threads
## [HIGH:70] Issue Found by Staging CI Review

**Severity:** HIGH
**Confidence:** 70/100
**PR comment:** https://github.com/nearai/ironclaw/pull/1483#issuecomment-4100594194

### Description
Incomplete fallback logic for non-existent approval threads

---
*Auto-created by staging-ci Claude Code review*

### PR DESCRIPTION
**Pull request by zmanian**
## Summary

Consolidates two security fixes for the approval processing flow in `thread_ops.rs`:

- **TOCTOU race (#1486):** Hold session lock for the entire take-verify sequence in `process_approval()` so pending approval cannot be lost if a concurrent operation modifies the thread between take and restore. Previously, the lock was dropped after `take_pending_approval()` and re-acquired for `request_id` verification, creating a window where the approval could be permanently lost.

- **Silent error fallback (#1487):** Replace 10 silent `if let Some(thread)` patterns with explicit `match` arms. Critical paths (state transitions, deferred approval setup) return errors when threads disappear. Non-critical paths (tool result recording, auth mode, rejection) log debug messages but continue.

## Files changed
- `src/agent/thread_ops.rs` — both fixes + 2 regression tests

## Test plan
- [x] Regression test: `test_approval_request_id_mismatch_restores_pending`
- [x] Regression test: `test_approval_on_missing_thread_should_error`
- [x] `cargo check` clean
- [x] Zero clippy warnings
- [ ] CI: full test suite (local env too memory-constrained for test binary linking)

Supersedes #1591 (branch had no merge base with current staging after repo restructuring).
Closes #1486, Closes #1487

https://claude.ai/code/session_01X86EZxqXEFiU9VetyhPKjM

### CODE REVIEW

File: src/agent/thread_ops.rs [hunk 1]
```diff
@@ -1868,17 +1896,25 @@ impl Agent {
...
+                            &message.channel,
+                            &message.user_id,
+                            &rejection,
+                        )
+                        .await;
+                    }
+                    None => {
+                        tracing::debug!(
+                            %thread_id,
+                            "Thread disappeared before rejection could be recorded"
```
Comment (serrrfirat) [inline src/agent/thread_ops.rs]: **High — Rejection path returns success when thread is gone**

When the thread disappears before rejection can be recorded, the function logs a debug message but still sends `StatusUpdate::Status("Rejected")` and returns `SubmissionResult::response(rejection)`. The caller and UI see a successful rejection for a thread that no longer exists.

More critically, the pending approval was already `take()`-n at line 1181 and consumed. If the thread disappears between take and the rejection path, the approval is permanently lost with no error surfaced.

**Suggested fix:** The `None` arm for the rejection branch should return an error (like the approval-path critical sites at lines 1267-1274 and 1691-1697), e.g., `SubmissionResult::error("Thread disappeared during rejection")`.

File: src/agent/thread_ops.rs [hunk 2]
```diff
@@ -1358,15 +1361,26 @@ impl Agent {
...
+                                    &pending.tool_call_id,
+                                    serde_json::json!(result_content),
+                                );
+                            }
+                        }
+                    }
+                    None => {
+                        tracing::debug!(
+                            %thread_id,
+                            "Thread disappeared before tool result could be recorded"
```
Comment (serrrfirat) [inline src/agent/thread_ops.rs:1386]: **Medium — Tool result recording silently continues when thread gone**

When the thread disappears before the tool result can be recorded, the code logs debug and continues. But the tool has already been executed (line 1307-1308). The `context_messages` still get the tool result appended (line 1389-1393), so the agentic loop may resume with context referencing a tool call whose result was never persisted in the thread.

This is partially mitigated by the error at line 1769-1770 but could cause a mismatch between LLM context and persisted state. A comment explaining why proceeding is safe would clarify intent.

File: src/agent/thread_ops.rs [hunk 3]
```diff
@@ -1911,17 +1947,25 @@ impl Agent {
...
+                        &message.channel,
+                        &message.user_id,
+                        &instructions,
+                    )
+                    .await;
+                }
+                None => {
+                    tracing::debug!(
+                        %thread_id,
+                        "Thread disappeared before auth intercept could be applied"
```
Comment (serrrfirat) [inline src/agent/thread_ops.rs:1968]: **Medium — Orphaned SSE emission for dead thread**

When the thread disappears, the `None` arm logs debug but execution continues past the block to `emit_auth_required_status()`. This sends an `AuthRequired` SSE event to the client for a thread that no longer exists. The client will show an auth prompt that can never be completed. The caller (`process_approval`) subsequently returns `SubmissionResult::auth_pending()` for a dead thread.

**Suggested fix:** Return early from `handle_auth_intercept` when the thread is gone, or suppress the SSE emission.

File: src/agent/thread_ops.rs [hunk 4]
```diff
@@ -2031,8 +2081,16 @@ impl Agent {
...
-                    if let Some(thread) = sess.threads.get_mut(&thread_id) {
-                        thread.enter_auth_mode(pending.extension_name.clone());
+                    match sess.threads.get_mut(&thread_id) {
+                        Some(thread) => {
+                            thread.enter_auth_mode(pending.extension_name.clone());
+                        }
+                        None => {
+                            tracing::debug!(
+                                %thread_id,
+                                "Thread disappeared before auth mode could be re-entered"
```
Comment (serrrfirat) [inline src/agent/thread_ops.rs:2093]: **Medium — Orphaned SSE emission in `process_auth_token`**

Two code paths in `process_auth_token` (the `Ok(result)` and `Err(e)` arms) re-enter auth mode. When the thread is gone, the `None` arm logs debug but execution continues to `emit_auth_required_status()`. This sends auth-required SSE events for a nonexistent thread.

**Suggested fix:** Add early return or skip the `emit_auth_required_status` call when the thread was not found.

**Review by serrrfirat — DISMISSED** [review]
## Paranoid Architect Review — REQUEST CHANGES

**1 High, 4 Medium findings.**

The core TOCTOU fix (holding the lock for take-verify) is correct and the regression test validates it well. However, the silent-error-fallback fix is **inconsistently applied**:

- **High:** The rejection path returns success to the caller when the thread is gone, permanently losing the approval with no error.
- **Medium:** Two `handle_auth_intercept` / `process_auth_token` paths emit SSE events for dead threads — clients get stuck in auth prompts that can never resolve.
- **Medium (Finding 5 — not in diff, line ~374):** One `if let Some(thread)` pattern at line ~374 in `process_user_input` (the Processing/queue path) was **not converted**, contrary to the PR's stated scope of "Replace 10 silent `if let Some(thread)` patterns." If the thread disappears between the state snapshot (line 344) and the mutable re-lock (line 373), the code silently falls through to the `Idle | Completed` match arm, which could incorrectly start a new turn on a removed thread. **Suggested fix:** Convert this to a `match` with explicit `None` handling, consistent with the other 9 sites.

The rejection path (finding #1) is the ship-blocker — it should return an error, not success, matching the approval path's behavior.

**Review by serrrfirat — DISMISSED** [review]
## Paranoid Security Review — NEEDS CHANGES

**PR:** #2366 — Harden approval thread safety (TOCTOU + error handling)
**Reviewer context:** Automated deep security review

### High

**Rejection path returns success when thread disappears.** The rejection branch converts `if let Some(thread)` to a `match` with a `None` arm that logs debug but continues. After the block, the code still sends `StatusUpdate::Status("Rejected")` and returns `SubmissionResult::response(rejection)`. The pending approval was already consumed by `take_pending_approval()`, the rejection was never persisted (thread is gone), but the caller sees a successful rejection. The approval is permanently lost with no error surfaced. Should return an error, matching the approval path's behavior.

**Orphaned SSE emissions in `handle_auth_intercept` and `process_auth_token`.** Converted sites log debug when the thread is gone but continue to `emit_auth_required_status()`. This sends auth-required SSE events for nonexistent threads — clients display auth prompts that can never complete. Add early returns.

### Medium

- **`process_user_input` line 374 not converted.** If the thread disappears between the state snapshot (line 354) and the mutable re-lock (line 374), execution silently falls through to the `Idle | Completed` arm, starting a new turn on a nonexistent thread. This was in the stated scope of "replacing 10 silent `if let Some(thread)` patterns."
- **No concurrent stress test.** The regression tests are excellent for single-threaded scenarios, but there's no test that spawns two `process_approval` tasks simultaneously to verify only one succeeds.

### Low

- Misleading title says "TOCTOU + atomics" but no `std::sync::atomic` types are used — the fix uses `tokio::sync::Mutex` lock holds. The description body is accurate ("TOCTOU + error handling").

### Summary

The core TOCTOU fix is correct and well-targeted — consolidating take/verify/restore into a single lock hold eliminates the race. The ship-blockers are the rejection path returning success on thread disappearance and the orphaned SSE emissions. Both are straightforward fixes.

File: src/agent/thread_ops.rs (hunk 1 above)
Comment (zmanian) [reply src/agent/thread_ops.rs]: Finding #1 was already addressed in the original PR — the rejection path returns `Err(JobError::NotFound)` at line 1888 when the thread is gone.

File: src/agent/thread_ops.rs (hunk 2 above)
Comment (zmanian) [reply src/agent/thread_ops.rs:1386]: Added explanatory comment: the tool result is still appended to context_messages so the LLM sees a matching tool_result for every tool_use ID (mismatches cause API errors). The missing thread will be detected on the next agentic loop iteration.

File: src/agent/thread_ops.rs (hunk 3 above)
Comment (zmanian) [reply src/agent/thread_ops.rs:1968]: Fixed in 6fee0ae8. `handle_auth_intercept` now returns early in the `None` arm, preventing orphaned auth-required SSE events for dead threads.

File: src/agent/thread_ops.rs (hunk 4 above)
Comment (zmanian) [reply src/agent/thread_ops.rs:2093]: Fixed in 6fee0ae8. Both `Ok(result)` and `Err(e)` retry paths in `process_auth_token` now check `thread_alive` before emitting `emit_auth_required_status`. Dead threads no longer receive auth prompts.

**Comment by zmanian** [comment]
All findings from both review rounds are addressed in the current branch:

- **Finding 1 (High - rejection path):** Fixed in 1e93133a. The rejection `None` arm returns `Err(JobError::NotFound)` at line 1916, matching the approval path's behavior.
- **Finding 5 (Medium - line 374 not converted):** Fixed in 6fee0ae8. Line 374 now uses `match sess.threads.get_mut(&thread_id) { Some(thread) => { ... } None => { ... } }` with explicit `None` handling, consistent with all other sites.
- **Orphaned SSE findings:** Fixed in 6fee0ae8 (`handle_auth_intercept` and `process_auth_token` paths).

**Review by serrrfirat — APPROVED** [review]
Reviewed as paranoid architect. TOCTOU fix is correct — lock held atomically for take-verify-restore. All 10 silent `if let Some` patterns properly categorized (critical → error, non-critical → debug log). No correctness bugs, no security concerns, no convention violations. Clean PR.
