### PR TITLE
fix(web): use conversation-only chat sidebar

### LINKED ISSUE #2857: [QA] Chat history list disappears from sidebar
### Environment

hosted-staging (crab shack)

### Version / Commit Hash

hosted-staging (crab shack) 2026-04-22

### QA Test Date

2026-04-22

### Feature Area

Web UI / chat sidebar

### Steps to Reproduce

1. Open the chat interface with existing conversations visible in the sidebar
2. Navigate or perform actions in the app (e.g., refresh or switch tabs)
3. Observe the sidebar conversation list

### Expected Behavior

The sidebar should display the full list of existing conversations consistently.

### Actual Behavior

All previous chats disappear from the sidebar, leaving only a "New chat" item. The conversation history is wiped from the UI. This makes it impossible to return to prior conversations without a workaround. The conversations may still exist on the backend but are not rendered in the sidebar.

### Logs / Screenshots

_No response_

### Pre-submit checklist

- [x] Title is specific (not "fix Google Suite" but "Google Suite install throws invalid_grant on OAuth step")
- [x] Commit hash is filled in
- [x] Steps are numbered and reproducible

### PR DESCRIPTION
**Pull request by serrrfirat**
## Summary
- remove the special pinned assistant row from the web chat sidebar and render a single conversation list
- treat the legacy assistant conversation like a normal row in the sidebar while preserving first-user-message titles
- add targeted regression coverage for sidebar rendering and refresh fallback behavior

## Verification
- `cargo test test_chat_threads_handler_hides_engine_threads_and_keeps_conversation_titles -- --nocapture`
- `cargo test test_chat_history_returns_engine_channel_hint_without_renderable_messages -- --nocapture`
- `cargo test test_chat_threads_handler_returns_in_memory_threads_without_db -- --nocapture`
- `cd tests/e2e && .venv/bin/python -m pytest scenarios/test_chat.py -k first_gateway_conversation_appears_in_conversation_list -q --timeout=900`
- `cd tests/e2e && .venv/bin/python -m pytest scenarios/test_sse_reconnect.py -k 'refresh_without_hash_reopens_active_thread_history or refresh_skips_readonly_external_active_thread' -q --timeout=900`

## Notes
- manual local validation confirmed the sidebar now looks correct
- keeps engine execution threads out of the conversation list

### CODE REVIEW

File: crates/ironclaw_gateway/static/js/core/history.js [hunk 1]
```diff
@@ -389,38 +389,16 @@ function loadThreads() {
...
-        spinner.className = 'thread-processing';
-        spinner.innerHTML = '<div class="spinner"></div>';
-        el.appendChild(spinner);
-      }
-    }
+    const threads = [];
+    // Render one conversation list. The backend may still expose the legacy
+    // assistant conversation separately, but the sidebar should treat it like
+    // any other conversation row instead of pinning it above the list.
+    if (data.assistant_thread) threads.push(data.assistant_thread);
```
Comment (henrypark133) [inline crates/ironclaw_gateway/static/js/core/history.js:396]: Nice simplification. Folding assistant_thread into the normal sorted conversation list removes a lot of special-case sidebar behavior without giving up the active-thread restore and writable-thread fallback logic below.

File: tests/e2e/scenarios/test_sse_reconnect.py [hunk 2]
```diff
@@ -235,17 +232,38 @@ async def test_refresh_without_hash_reopens_active_thread_history(browser, manag
 
 async def test_refresh_skips_readonly_external_active_thread(page):
```
Comment (henrypark133) [inline tests/e2e/scenarios/test_sse_reconnect.py:233]: Good coverage addition here. This pins the exact refresh edge case the UI refactor could have broken: skipping a read-only external active thread while still reopening a writable gateway conversation and keeping the composer enabled.

**Review by henrypark133 — DISMISSED** [review]
This looks good to me. The refactor removes the pinned-assistant special case cleanly, keeps the active-thread and read-only fallback behavior intact, and adds focused E2E coverage for the sidebar/refresh regressions that would have worried me most here.
