### PR TITLE
fix(routines): normalize status display across web and CLI

### LINKED ISSUE #1319: Routines: status surfaces should distinguish running, attention, and dispatched states
## Summary

Routine status surfaces flatten meaningful states. The web and CLI mainly derive routine status from `enabled` plus `consecutive_failures`, which hides `running`, `attention`, and "job dispatched but still executing" states.

## Evidence

- `RoutineInfo::from_routine()` only emits `disabled`, `failing`, or `active`.
- The routines web list/detail maps only those coarse states.
- CLI list output similarly compresses status to `active` or `err(n)`.

Relevant references:

- `src/channels/web/types.rs:825-845`
- `src/channels/web/static/app.js:3753-3770`
- `src/channels/web/static/app.js:3802-3807`
- `src/cli/routines.rs:255-260`
- Audit doc: `docs/plans/2026-03-17-routines-deep-dive.md`

## Expected Behavior

Users should be able to distinguish at least:

- currently running
- last run needed attention
- last run failed
- job dispatched and still executing
- disabled

## Coverage Requirement

- Add UI-facing coverage for a routine whose last completed run is `attention` and verify list/detail do not still show plain `active`.
- Add coverage for an in-flight `full_job` routine and verify the surfaced status reflects active execution rather than idle success.
- Add CLI coverage for the same states if the CLI is expected to remain a supported management surface.

### PR DESCRIPTION
**Pull request by zmanian**
## Summary
- Fixes Debug vs Display formatting bug in web API: `format!("{:?}", run.status)` -> `run.status.to_string()` for consistent lowercase status values
- Updates JavaScript status class mapping to match lowercase values (`ok`, `failed`, `attention`, `running`)
- Enriches CLI `routines list` to show `running` and `attention` states instead of just `active`/`err(N)`/`disabled`

Closes #1319

## Test plan
- [x] Clippy clean with `--all-features`
- [x] All routines-related tests pass
- [ ] Manual: verify web UI routine badges render correctly with lowercase status values
- [ ] Manual: verify `ironclaw routine list` shows enriched status column

### CODE REVIEW

File: src/cli/routines.rs [hunk 1]
```diff
@@ -251,15 +251,38 @@ async fn list(
     );
     println!("{}", "-".repeat(130));
 
+    // Fetch last-run status for all routines in parallel to avoid N+1 queries
+    let last_run_futures: Vec<_> = filtered
+        .iter()
+        .map(|r| async {
+            let status = db
```
Comment (serrrfirat) [inline src/cli/routines.rs]: **High Severity: N+1 Query Performance Bug**

This code introduces a classic N+1 query problem:

```rust
let last_run_futures: Vec<_> = filtered
    .iter()
    .map(|r| async {
        let status = db
            .list_routine_runs(r.id, 1)  // ⚠️ Separate query for EACH routine
            .await
            .ok()
            .and_then(|runs| runs.into_iter().next())
            .map(|run| run.status);
        (r.id, status)
    })
    .collect();
```

**Impact:** If there are 100 routines, this fires **101 queries** (1 for `list_routines` + 100 for last run status). This will:
- Be extremely slow on large installations (10+ seconds for 100 routines)
- Risk database connection pool exhaustion
- Potentially cause timeouts

**Why `join_all` doesn't help:** While `futures::future::join_all` runs the queries concurrently, you're still executing N separate DB queries. This overwhelms the connection pool and the database.

**Fix:** Batch-fetch all last-run statuses in a single query:
1. **Best option:** Modify `list_routines()` to include `last_run_status` via a LEFT JOIN:
   ```sql
   SELECT r.*, lr.status as last_run_status
   FROM routines r
   LEFT JOIN LATERAL (
     SELECT status FROM routine_runs 
     WHERE routine_id = r.id 
     ORDER BY started_at DESC LIMIT 1
   ) lr ON true
   ```
2. **Alternative:** Add a new method `db.batch_get_last_run_status(&routine_ids)` that fetches all in one query using `WHERE routine_id = ANY()` (PostgreSQL) or `WHERE routine_id IN (...)` (libSQL).

Comment (zmanian) [reply src/cli/routines.rs]: Fixed in 0016e54d. Added `batch_get_last_run_status` to the `Database` trait with implementations for both backends:

- **PostgreSQL**: Uses `DISTINCT ON (routine_id) ... ORDER BY routine_id, started_at DESC` to pick the latest run per routine in a single query.
- **libSQL**: Queries all latest runs via a correlated subquery (`WHERE started_at = (SELECT MAX(started_at) ...)`), then filters in memory to the requested IDs (same pattern as the existing `count_running_routine_runs_batch`).

The CLI now collects all routine IDs upfront and calls the batch method once instead of N times. Added 4 integration tests covering empty input, latest-status selection, omission of routines without runs, and multiple routines with different statuses.

**Comment by zmanian** [comment]
Addressed N+1 query feedback in 0016e54d:

- Added `batch_get_last_run_status(&[Uuid]) -> HashMap<Uuid, RunStatus>` to `RoutineStore` trait
- PostgreSQL: single query using `DISTINCT ON (routine_id)` with `ANY($1)`
- libSQL: correlated subquery with `GROUP BY routine_id`
- Replaced `join_all` of per-routine queries with single batch call in `src/cli/routines.rs`
- Added 4 integration tests covering edge cases (empty input, no runs, multiple routines)
