### PR TITLE
fix(slack): remember thread participation across replies

### LINKED ISSUE #1404: Slack channel ignores thread replies in channels without @mention
## Description

When a user @mentions the bot in a Slack channel and the bot replies in a thread, subsequent messages in that same thread are ignored unless the user @mentions the bot again on every message. This breaks conversational flow in channels.

## Steps to Reproduce

1. @mention the bot in a Slack channel (e.g., `@TARS AI, hello`)
2. Bot replies in a thread
3. Reply in the thread **without** @mention (e.g., `what's the weather?`)
4. Bot does not respond

## Expected Behavior

The bot should respond to follow-up messages in threads where it has already participated, without requiring @mention on every message. This is the standard behavior users expect from Slack bots (e.g., how Slack's own AI or other bots handle threads).

## Root Cause

Two issues found:

### 1. Slack WASM channel only processes DMs in the \`message\` handler

In \`channels-src/slack/src/lib.rs\`, the \`"message"\` event handler (around line 500) only processes direct messages:

\`\`\`rust
if channel.starts_with('D') {
    // Only DMs are processed
}
\`\`\`

Thread replies in channels arrive as \`"message"\` events (not \`"app_mention"\`), so they are silently dropped.

### 2. Host \`on_respond\` callback never commits workspace writes

In \`src/channels/wasm/wrapper.rs\`, the \`call_on_respond\` method does not call \`take_pending_writes()\` + \`commit_writes()\` after WASM execution, unlike \`on_start\`, \`on_http_request\`, and \`on_poll\`. It also does not call \`inject_workspace_reader\`. This means any WASM channel that tries to persist state during \`on_respond\` silently loses that data.

## Environment

- IronClaw v0.19.0
- Slack Events API (webhook mode, not Socket Mode)
- Event subscriptions: \`app_mention\`, \`message.channels\`, \`message.groups\`, \`message.im\`

### PR DESCRIPTION
**Pull request by G7CNF**
Fixes #1404.\n\nSlack thread replies in channels are now accepted once the bot has already joined that thread, instead of requiring a fresh @mention on every follow-up. The Slack WASM channel now records active thread IDs when it posts a threaded reply, and the host now persists on_respond workspace writes so that participation memory survives across callbacks.\n\nValidation:\n- cargo fmt --all -- --check\n- cargo test --manifest-path channels-src/slack/Cargo.toml\n- cargo clippy -p ironclaw --lib --all-features -- -D warnings

### CODE REVIEW

**Review by ilblackdragon — CHANGES_REQUESTED** [review]
## Review: fix(slack): remember thread participation across replies

### Must-fix (fix the pattern, not just the instance)

1. **`call_on_broadcast` has the exact same bug** — uses `self.capabilities.clone()` without `inject_workspace_reader` and doesn't call `take_pending_writes`/`commit_writes`. Feishu/other channels calling `send_message()` from `on_broadcast` will fail workspace reads.

2. **`call_on_status` also lacks workspace write persistence** — same pattern.

### Should-fix

3. **Unbounded thread accumulation** — the `active_threads` set grows without bound. No eviction or TTL. A long-running bot accumulates thousands of thread timestamps. Add a size cap (e.g., LRU eviction at 1000 entries) or TTL-based pruning.

4. **Security model note** — once the bot joins a thread, any user in the workspace can talk to it by replying in that thread, bypassing pairing/allow_from restrictions. This matches `app_mention` behavior but should be documented.

### Nit

5. `sorted.sort()` → `sorted.sort_unstable()` since thread timestamps are unique strings and stable ordering doesn't matter.

**Comment by serrrfirat** [comment]
Pushed `706d6b09` to the PR head branch to address the open feedback.

What changed:
- Scoped Slack active-thread memory by `team_id + channel + thread_ts` instead of bare `thread_ts`.
- Stopped persisting DM thread IDs, since DMs are always accepted and do not need active-thread tracking.
- Kept backward compatibility for the old `Vec<String>` active-thread format.
- Added Slack regression coverage for structured keys, legacy keys, and cross-channel/team non-matches.
- Centralized WASM callback workspace-write commits and added regression coverage that an `on_respond`-style workspace write reaches the persistent store for later callback reads.

Checks run:
- `cargo fmt --all -- --check`
- `git diff --check`
- `cargo test --manifest-path channels-src/slack/Cargo.toml`
- `cargo test --features libsql test_on_respond_workspace_write_commit_survives_later_callback -- --nocapture`

File: channels-src/slack/src/lib.rs [hunk 1]
```diff
@@ -561,6 +587,83 @@ fn emit_message(
...
+    if threads.contains(&key) {
+        return;
+    }
+
+    threads.insert(key);
+    let _ = channel_host::workspace_write(
+        ACTIVE_THREADS_PATH,
+        &serialize_active_slack_threads(&threads),
+    );
+}
```
Comment (ilblackdragon) [inline channels-src/slack/src/lib.rs:843]: **High — Unbounded state growth (DoS / perf).** The new `HashSet<ActiveSlackThread>` has no TTL and no max-size cap. Each thread the bot replies to adds an entry forever, and `remember_active_slack_thread` reads → deserializes → mutates → serializes → rewrites the entire blob on every outbound message, and `is_active_slack_thread` does the same read+parse on every inbound channel message.

For a long-running workspace (months, 1000s of threads) this becomes:
- Quadratic cost: O(n) deserialize per inbound/outbound Slack event, for n threads accumulated over the channel's lifetime.
- An attacker who can DM or mention the bot can cheaply grow n; each message after that costs more.
- Workspace blob grows unboundedly in the in-memory store and in whatever persistent workspace backs it.

Compare to the pattern that existed earlier on this branch (BTreeMap with `ACTIVE_THREAD_TTL_MS = 24h` and `ACTIVE_THREAD_MAX_ENTRIES = 256` plus `prune_active_threads`) — that design explicitly bounded both age and count. Removing it regressed the DoS surface.

Please reintroduce at least one of:
- a `last_seen_ms` field + TTL-based pruning on read+write, or
- a hard cap (drop oldest by insertion order or by `last_seen`).

Otherwise this is effectively "bot remembers every thread it has ever touched".

File: channels-src/slack/src/lib.rs [hunk 2]
```diff
@@ -561,6 +587,83 @@ fn emit_message(
...
+        parse_active_slack_threads(channel_host::workspace_read(ACTIVE_THREADS_PATH).as_deref());
+    if threads.contains(&key) {
+        return;
+    }
+
+    threads.insert(key);
+    let _ = channel_host::workspace_write(
+        ACTIVE_THREADS_PATH,
+        &serialize_active_slack_threads(&threads),
+    );
```
Comment (ilblackdragon) [inline channels-src/slack/src/lib.rs]: **High — Read-modify-write race / lost updates.** `remember_active_slack_thread` and `is_active_slack_thread` both do a full read → parse → mutate → serialize → write against `ACTIVE_THREADS_PATH` with no serialization between callback invocations.

The host (`src/channels/wasm/wrapper.rs`) runs each Slack callback in its own `spawn_blocking` task with no per-channel execution lock (grep `call_on_respond`, `call_on_http_request` — no `Mutex` guarding them). So two concurrent `on_respond`s (e.g. agent replies to two different messages in quick succession) can both:
1. Read workspace blob `{A}`
2. Insert their own thread → `{A, B}` / `{A, C}` in their own WASM memory
3. `workspace_write` back — whichever commits second wins, silently dropping the other thread.

Same race between an `on_respond` (writing) and `on_http_request` (reading for the gate) — the gate can see a stale snapshot and reject a legitimate follow-up.

Because `ChannelWorkspaceStore` is backed by a plain `RwLock<HashMap>` with last-write-wins semantics (`src/channels/wasm/host.rs:527`), this is not a host concern that will be fixed separately — the WASM channel has no primitive to do this atomically. Mitigation options:
- Serialize `on_respond`/`on_http_request` callbacks per-channel in the host, **or**
- Add a host primitive like `workspace_append_unique(path, item)` that makes the add atomic on the host side, **or**
- Partition per-thread (one workspace key per thread) so concurrent writes don't collide.

As-is the state is advisory, not reliable.

File: channels-src/slack/src/lib.rs [hunk 3]
```diff
@@ -129,6 +137,8 @@ const OWNER_ID_PATH: &str = "state/owner_id";
 const DM_POLICY_PATH: &str = "state/dm_policy";
 /// Workspace path for persisting allow_from (JSON array) across WASM callbacks.
 const ALLOW_FROM_PATH: &str = "state/allow_from";
+/// Workspace path for thread timestamps the bot has already joined.
+const ACTIVE_THREADS_PATH: &str = "state/active_threads";
```
Comment (ilblackdragon) [inline channels-src/slack/src/lib.rs:149]: **High — "Participation memory" does not survive process restart.** The PR body says *"participation memory survives across callbacks"*, and the wrapper.rs change correctly fixes the in-flight persistence bug. But `ChannelWorkspaceStore` is a process-local `RwLock<HashMap<String, String>>` (`src/channels/wasm/host.rs:514-524`):

```rust
pub struct ChannelWorkspaceStore {
    data: std::sync::RwLock<std::collections::HashMap<String, String>>,
}
```

Nothing flushes this to disk or a database. On every IronClaw restart (which is the most common operational event — config changes, deploys, crashes, `cargo run` in dev) the set is wiped and every thread the bot previously joined becomes "unknown". Issue #1404's symptom ("I replied once but now the bot ignores my follow-ups") will return the first time the process is restarted.

This likely needs to be persisted through the same backend that handles `state/owner_id`, `state/dm_policy`, `state/allow_from` — per `CLAUDE.md`, new persistence features must support both PostgreSQL and libSQL. If `channel_host::workspace_write` isn't already DB-backed for Slack, that's the root fix; if it is, please confirm with a test that round-trips across a restart. Either way the PR description is currently inaccurate — suggest re-wording to "survives across callbacks within a single process lifetime" and filing a follow-up for cross-restart durability.

File: channels-src/slack/src/lib.rs [hunk 4]
```diff
@@ -826,4 +929,81 @@ mod tests {
...
+            Some("T2"),
+            "C1",
+            "123.45"
+        ));
+    }
+
+    #[test]
+    fn test_active_slack_threads_ignore_invalid_json() {
+        assert!(parse_active_slack_threads(Some("not-json")).is_empty());
+        assert!(parse_active_slack_threads(None).is_empty());
```
Comment (ilblackdragon) [inline channels-src/slack/src/lib.rs]: **Medium — Missing caller-level regression test** (per `.claude/rules/testing.md` "Test Through the Caller, Not Just the Helper").

The four new unit tests exercise the pure helpers (`parse_active_slack_threads`, `serialize_active_slack_threads`, `active_slack_thread_is_known`). But the actual gate the PR is trying to fix — *does a `message` event with `thread_ts` get through to `emit_message`* — lives in `handle_slack_event` (lines 507-540), which sits behind the wrapper `is_active_slack_thread` → `channel_host::workspace_read`. None of the tests exercise that path.

That is exactly the shape the rule calls out: predicate (`active_slack_thread_is_known`) gates a side effect (`emit_message`) with a wrapper (`is_active_slack_thread`) that computes inputs (pulls from workspace_read). A future refactor that silently changes the channel/team_id passed in, or that breaks how `workspace_read` is wired into the capabilities injector, would not fail any test in this PR.

Minimum additional coverage:
- A test driving `handle_slack_event` with a `message` `SlackEvent` whose `thread_ts` is in the active set → expect `emit_message` called.
- Same with `thread_ts` NOT in the set → expect no emit.
- Same after a simulated restart (drop the store, reconstruct) — expect no emit (which is also the regression test for the High comment about restart durability once that's fixed).

The bot→`channel_host` boundary makes pure helper unit tests especially weak here, since the real failure modes (reader not injected, write not committed) are in the host wiring.

File: src/channels/wasm/wrapper.rs [hunk 5]
```diff
@@ -1181,6 +1181,14 @@ impl WasmChannel {
         )
     }
 
+    fn commit_callback_workspace_writes(
+        host_state: &mut ChannelHostState,
+        workspace_store: &ChannelWorkspaceStore,
+    ) {
+        let pending_writes = host_state.take_pending_writes();
+        workspace_store.commit_writes(&pending_writes);
+    }
```
Comment (ilblackdragon) [inline src/channels/wasm/wrapper.rs:1747]: **Medium — Latent inconsistency: `call_on_broadcast` and `call_on_status` skip the reader injection + commit helper.** This PR correctly adds `inject_workspace_reader` + `commit_callback_workspace_writes` to `call_on_respond`, matching `call_on_start`, `call_on_http_request`, and `call_on_poll`. Good.

But `call_on_broadcast` (line 1716: `let capabilities = self.capabilities.clone();`) and `call_on_status` (line 1823) still use the raw capabilities and never call `commit_callback_workspace_writes`. Slack's `on_broadcast` is currently a stub (`Err("not yet implemented")`), so this PR doesn't expose the bug in Slack — but any other WASM channel calling `workspace_read`/`workspace_write` inside those callbacks will:

- `workspace_read` returns `None` (reader not wired) → reads of previously-written state get nothing, identical to the bug this PR is fixing for `on_respond`.
- `workspace_write` silently vanishes when the `ChannelHostState` is dropped at the end of the callback without `commit_callback_workspace_writes`.

Since `commit_callback_workspace_writes` is now a helper precisely to make this wiring uniform, please apply it to the remaining two call sites (or add a comment documenting why they're deliberately excluded).

**Comment by ilblackdragon** [comment]
### Review summary

Thanks for tackling #1404. The core idea — remember threads the bot has participated in, and let follow-ups through the inbound gate — is right, and the `wrapper.rs` half (injecting the reader and committing pending writes in `on_respond`) is a real bug fix that was independently needed.

The Slack-side half is not ready to merge in its current form. Three blocking concerns (line comments posted):

1. **No TTL and no max-size** on the `HashSet<ActiveSlackThread>`. A previous revision on this branch had both (`ACTIVE_THREAD_TTL_MS = 24h`, `ACTIVE_THREAD_MAX_ENTRIES = 256`, `prune_active_threads`). Dropping those regressed the DoS surface and makes every message O(n) where n grows unboundedly.

2. **Read-modify-write race across concurrent callbacks.** `remember_active_slack_thread` does a full read-parse-mutate-serialize-write cycle with no per-channel callback lock, so concurrent `on_respond`s silently lose thread entries.

3. **State is in-memory only.** `ChannelWorkspaceStore` is a process-local `RwLock<HashMap>`; the PR description's claim that participation memory "survives across callbacks" is true within a process but false across restarts. The #1404 symptom reappears on every restart.

Plus two medium items:

4. Missing caller-level regression test for `handle_slack_event` (the rule in `.claude/rules/testing.md` — unit tests only cover the pure helpers, not the path that actually gates emit).
5. `call_on_broadcast` and `call_on_status` still skip `inject_workspace_reader` + `commit_callback_workspace_writes` — latent bug for other WASM channels.

Suggested sequencing for the next revision:
- Restore the TTL+cap design (simpler than fully fixing the race, and bounds the damage from it).
- Route through a durable workspace (same as `owner_id`/`dm_policy`), dual-backend per `CLAUDE.md`.
- Add at least one test that drives `handle_slack_event` end-to-end with a mocked workspace reader.
- Apply the commit helper to the remaining two callbacks.

Verdict: **request changes** on architecture (durability + bounding); nothing security-critical, but the feature won't deliver what the PR body promises.

**Comment by serrrfirat** [comment]
Addressed the review feedback in `ea4a0fc4`.

Summary:
- made Slack thread participation state restart-stable via durable channel workspace persistence
- bounded active-thread state with TTL + max-entry pruning, and documented thread visibility semantics
- serialized WASM channel callbacks to avoid lost updates and aligned `on_status` workspace read/write commit behavior with the other callbacks
- added caller-level Slack regression coverage plus durable workspace restore coverage

Targeted validation:
- `cargo fmt --all`
- `cargo test --manifest-path channels-src/slack/Cargo.toml --quiet`
- wrapper regression tests for broadcast/status persistence + durable restore
- `cargo clippy --all --benches --tests --examples --all-features`

Re-requested review from @ilblackdragon.

**Review by serrrfirat — APPROVED** [review]
